name: Run climate data script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update_data:
    name: Update data with newest climate data
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt
 
      - name: Run Script
        env:
            DATAWRAPPER_ACCESS_TOKEN: ${{ secrets.DATAWRAPPER_ACCESS_TOKEN }}
        run: |
             python klimadaten.py
